name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # Specify the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Update to v3 for the latest Node version support

    - name: Install Node.js
      uses: actions/setup-node@v3  # Update to v3 for Node.js support
      with:
        node-version: '20'  # Use Node 20 as suggested by the warning

    - name: Install Dependencies
      run: npm install

    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
      run: firebase deploy --only hosting
